name: doc

on:
  push:
    branches: [main]
    tags: v*
  pull_request:

jobs:
  doc:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install and configure poetry
      run: |
        python -m pip install poetry

    - name: Prepare project for development
      run: |
        python -m poetry run python -m pip install --upgrade pip
        python -m poetry install

    - name: Build documentation
      run: |
        poetry run invoke sphinx
