name: linters

on:
  push:
    branches: [main]
    tags: v*
  pull_request:

jobs:
  run_linters:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install and configure poetry
      run: |
        python -m pip install poetry

    - uses: extractions/setup-just@v1

    - name: Prepare project for development
      run: |
        just setup

    - name: Run linters
      run: |
        just lint

